use readonly_files
EESSI/test-suite pull request #220
Opened 2024-12-23 09:32 UTC by smoors

- update `CI/run_reframe.sh` to use a shared file system
- raise error if `readonly_files` is an empty list
- add `readonly_files` to all tests
- remove staging fixtures from `cp2k` and `lammps`
- remove `__init__.py` from `sourcesdirs`

2025-01-09 13:24 UTC, casparvl commented on eessi/testsuite/eessi_mixin.py
> +        if not cls.readonly_files:
Wait, does this work? Isn't this always true, because a default is set by ReFrame? https://reframe-hpc.readthedocs.io/en/stable/regression_test_api.html#reframe.core.pipeline.RegressionTest.readonly_files

2025-01-09 13:27 UTC, casparvl requested changes
Please don't remove the empty __init__ files, they are needed by the automatic API generation tools. Seems silly, but it is what it is :)

2025-01-09 13:28 UTC, casparvl commented
Note: I haven't tested this PR yet, I'll do that once we agree on the actual changes in the code :)

2025-01-09 15:51 UTC, smoors commented
> Note: I haven't tested this PR yet, I'll do that once we agree on the actual changes in the code :)

for reference: they were only removed from the src directories, but we agreed that it's useful to have a list of the sources in the docs too.
i'll add them back

2025-01-09 16:12 UTC, casparvl reviewed
Code changes look good to me (barring the `__init__` removals), now running 

```
reframe --system=snellius:rome -t CI -t '1_nodes|2_nodes' --run
```

just to test.

Update: all tests passed.

2025-01-13 14:57 UTC, casparvl approved these changes

2025-01-13 14:57 UTC, merged